package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.AdditionView;
import cn.bupt.smartyagl.entity.autogenerate.AdditionViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdditionViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdditionView
     *
     * @mbggenerated
     */
    int countByExample(AdditionViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdditionView
     *
     * @mbggenerated
     */
    int deleteByExample(AdditionViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdditionView
     *
     * @mbggenerated
     */
    int insert(AdditionView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdditionView
     *
     * @mbggenerated
     */
    int insertSelective(AdditionView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdditionView
     *
     * @mbggenerated
     */
    List<AdditionView> selectByExampleWithBLOBs(AdditionViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdditionView
     *
     * @mbggenerated
     */
    List<AdditionView> selectByExample(AdditionViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdditionView
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AdditionView record, @Param("example") AdditionViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdditionView
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") AdditionView record, @Param("example") AdditionViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdditionView
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AdditionView record, @Param("example") AdditionViewExample example);
}