package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.Advertise;
import cn.bupt.smartyagl.entity.autogenerate.AdvertiseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdvertiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertise
     *
     * @mbggenerated
     */
    int countByExample(AdvertiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertise
     *
     * @mbggenerated
     */
    int deleteByExample(AdvertiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertise
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertise
     *
     * @mbggenerated
     */
    int insert(Advertise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertise
     *
     * @mbggenerated
     */
    int insertSelective(Advertise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertise
     *
     * @mbggenerated
     */
    List<Advertise> selectByExample(AdvertiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertise
     *
     * @mbggenerated
     */
    Advertise selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertise
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Advertise record, @Param("example") AdvertiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertise
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Advertise record, @Param("example") AdvertiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertise
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Advertise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertise
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Advertise record);
}