package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.BlockManager;
import cn.bupt.smartyagl.entity.autogenerate.BlockManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlockManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManager
     *
     * @mbggenerated
     */
    int countByExample(BlockManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManager
     *
     * @mbggenerated
     */
    int deleteByExample(BlockManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManager
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManager
     *
     * @mbggenerated
     */
    int insert(BlockManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManager
     *
     * @mbggenerated
     */
    int insertSelective(BlockManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManager
     *
     * @mbggenerated
     */
    List<BlockManager> selectByExample(BlockManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManager
     *
     * @mbggenerated
     */
    BlockManager selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManager
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BlockManager record, @Param("example") BlockManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManager
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BlockManager record, @Param("example") BlockManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManager
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BlockManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManager
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BlockManager record);
}