package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.BlockManagerView;
import cn.bupt.smartyagl.entity.autogenerate.BlockManagerViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlockManagerViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BlockManagerView
     *
     * @mbggenerated
     */
    int countByExample(BlockManagerViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BlockManagerView
     *
     * @mbggenerated
     */
    int deleteByExample(BlockManagerViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BlockManagerView
     *
     * @mbggenerated
     */
    int insert(BlockManagerView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BlockManagerView
     *
     * @mbggenerated
     */
    int insertSelective(BlockManagerView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BlockManagerView
     *
     * @mbggenerated
     */
    List<BlockManagerView> selectByExample(BlockManagerViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BlockManagerView
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BlockManagerView record, @Param("example") BlockManagerViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BlockManagerView
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BlockManagerView record, @Param("example") BlockManagerViewExample example);
}