package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.BlockManagerMenu;
import cn.bupt.smartyagl.entity.autogenerate.BlockManagerMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlockManagerMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManagerMenu
     *
     * @mbggenerated
     */
    int countByExample(BlockManagerMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManagerMenu
     *
     * @mbggenerated
     */
    int deleteByExample(BlockManagerMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManagerMenu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManagerMenu
     *
     * @mbggenerated
     */
    int insert(BlockManagerMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManagerMenu
     *
     * @mbggenerated
     */
    int insertSelective(BlockManagerMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManagerMenu
     *
     * @mbggenerated
     */
    List<BlockManagerMenu> selectByExample(BlockManagerMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManagerMenu
     *
     * @mbggenerated
     */
    BlockManagerMenu selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManagerMenu
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BlockManagerMenu record, @Param("example") BlockManagerMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManagerMenu
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BlockManagerMenu record, @Param("example") BlockManagerMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManagerMenu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BlockManagerMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blockManagerMenu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BlockManagerMenu record);
}