package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.CollectView;
import cn.bupt.smartyagl.entity.autogenerate.CollectViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollectViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CollectView
     *
     * @mbggenerated
     */
    int countByExample(CollectViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CollectView
     *
     * @mbggenerated
     */
    int deleteByExample(CollectViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CollectView
     *
     * @mbggenerated
     */
    int insert(CollectView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CollectView
     *
     * @mbggenerated
     */
    int insertSelective(CollectView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CollectView
     *
     * @mbggenerated
     */
    List<CollectView> selectByExample(CollectViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CollectView
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CollectView record, @Param("example") CollectViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CollectView
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CollectView record, @Param("example") CollectViewExample example);
}