package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.CommentView;
import cn.bupt.smartyagl.entity.autogenerate.CommentViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CommentView
     *
     * @mbggenerated
     */
    int countByExample(CommentViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CommentView
     *
     * @mbggenerated
     */
    int deleteByExample(CommentViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CommentView
     *
     * @mbggenerated
     */
    int insert(CommentView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CommentView
     *
     * @mbggenerated
     */
    int insertSelective(CommentView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CommentView
     *
     * @mbggenerated
     */
    List<CommentView> selectByExampleWithBLOBs(CommentViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CommentView
     *
     * @mbggenerated
     */
    List<CommentView> selectByExample(CommentViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CommentView
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CommentView record, @Param("example") CommentViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CommentView
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") CommentView record, @Param("example") CommentViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CommentView
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CommentView record, @Param("example") CommentViewExample example);
}