package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.CookLeisure;
import cn.bupt.smartyagl.entity.autogenerate.CookLeisureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CookLeisureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookLeisure
     *
     * @mbggenerated
     */
    int countByExample(CookLeisureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookLeisure
     *
     * @mbggenerated
     */
    int deleteByExample(CookLeisureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookLeisure
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookLeisure
     *
     * @mbggenerated
     */
    int insert(CookLeisure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookLeisure
     *
     * @mbggenerated
     */
    int insertSelective(CookLeisure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookLeisure
     *
     * @mbggenerated
     */
    List<CookLeisure> selectByExampleWithBLOBs(CookLeisureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookLeisure
     *
     * @mbggenerated
     */
    List<CookLeisure> selectByExample(CookLeisureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookLeisure
     *
     * @mbggenerated
     */
    CookLeisure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookLeisure
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CookLeisure record, @Param("example") CookLeisureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookLeisure
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") CookLeisure record, @Param("example") CookLeisureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookLeisure
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CookLeisure record, @Param("example") CookLeisureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookLeisure
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CookLeisure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookLeisure
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CookLeisure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookLeisure
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CookLeisure record);
}