package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.FarmVisits;
import cn.bupt.smartyagl.entity.autogenerate.FarmVisitsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * 
 * @author TMing
 *
 */
public interface FarmVisitsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisits
     *
     * @mbggenerated Mon Oct 31 09:53:58 CST 2016
     */
    int countByExample(FarmVisitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisits
     *
     * @mbggenerated Mon Oct 31 09:53:58 CST 2016
     */
    int deleteByExample(FarmVisitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisits
     *
     * @mbggenerated Mon Oct 31 09:53:58 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisits
     *
     * @mbggenerated Mon Oct 31 09:53:58 CST 2016
     */
    int insert(FarmVisits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisits
     *
     * @mbggenerated Mon Oct 31 09:53:58 CST 2016
     */
    int insertSelective(FarmVisits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisits
     *
     * @mbggenerated Mon Oct 31 09:53:58 CST 2016
     */
    List<FarmVisits> selectByExample(FarmVisitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisits
     *
     * @mbggenerated Mon Oct 31 09:53:58 CST 2016
     */
    FarmVisits selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisits
     *
     * @mbggenerated Mon Oct 31 09:53:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") FarmVisits record, @Param("example") FarmVisitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisits
     *
     * @mbggenerated Mon Oct 31 09:53:58 CST 2016
     */
    int updateByExample(@Param("record") FarmVisits record, @Param("example") FarmVisitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisits
     *
     * @mbggenerated Mon Oct 31 09:53:58 CST 2016
     */
    int updateByPrimaryKeySelective(FarmVisits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisits
     *
     * @mbggenerated Mon Oct 31 09:53:58 CST 2016
     */
    int updateByPrimaryKey(FarmVisits record);
    
    /**
     * 批量插入参观类型
     * @param list
     * @return
     */
    int insertBatch(List<FarmVisits> list);
    
    /**
     * 批量查询参观类型
     * @param list
     * @return
     */
    List<FarmVisits> selectByIds(List<Integer> list);
    
    /**
     * 批量删除
     * @param id
     * @return
     */
    int deleteBatch(List<Integer> id);
    
    int batchUpdate(List<FarmVisits> list);
}