package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.FarmMessage;
import cn.bupt.smartyagl.entity.autogenerate.FarmMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FarmMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmMessage
     *
     * @mbggenerated
     */
    int countByExample(FarmMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmMessage
     *
     * @mbggenerated
     */
    int deleteByExample(FarmMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmMessage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmMessage
     *
     * @mbggenerated
     */
    int insert(FarmMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmMessage
     *
     * @mbggenerated
     */
    int insertSelective(FarmMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmMessage
     *
     * @mbggenerated
     */
    List<FarmMessage> selectByExampleWithBLOBs(FarmMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmMessage
     *
     * @mbggenerated
     */
    List<FarmMessage> selectByExample(FarmMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmMessage
     *
     * @mbggenerated
     */
    FarmMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmMessage
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FarmMessage record, @Param("example") FarmMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmMessage
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") FarmMessage record, @Param("example") FarmMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmMessage
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FarmMessage record, @Param("example") FarmMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmMessage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FarmMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmMessage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(FarmMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmMessage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FarmMessage record);
}