package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.FarmPhotos;
import cn.bupt.smartyagl.entity.autogenerate.FarmPhotosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FarmPhotosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmPhotos
     *
     * @mbggenerated
     */
    int countByExample(FarmPhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmPhotos
     *
     * @mbggenerated
     */
    int deleteByExample(FarmPhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmPhotos
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmPhotos
     *
     * @mbggenerated
     */
    int insert(FarmPhotos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmPhotos
     *
     * @mbggenerated
     */
    int insertSelective(FarmPhotos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmPhotos
     *
     * @mbggenerated
     */
    List<FarmPhotos> selectByExample(FarmPhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmPhotos
     *
     * @mbggenerated
     */
    FarmPhotos selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmPhotos
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FarmPhotos record, @Param("example") FarmPhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmPhotos
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FarmPhotos record, @Param("example") FarmPhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmPhotos
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FarmPhotos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmPhotos
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FarmPhotos record);
}