package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.Fre;
import cn.bupt.smartyagl.entity.autogenerate.FreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Fre
     *
     * @mbggenerated
     */
    int countByExample(FreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Fre
     *
     * @mbggenerated
     */
    int deleteByExample(FreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Fre
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Fre
     *
     * @mbggenerated
     */
    int insert(Fre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Fre
     *
     * @mbggenerated
     */
    int insertSelective(Fre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Fre
     *
     * @mbggenerated
     */
    List<Fre> selectByExample(FreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Fre
     *
     * @mbggenerated
     */
    Fre selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Fre
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Fre record, @Param("example") FreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Fre
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Fre record, @Param("example") FreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Fre
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Fre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Fre
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Fre record);
}