package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.GeneratedCardsOper;
import cn.bupt.smartyagl.entity.autogenerate.GeneratedCardsOperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GeneratedCardsOperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GeneratedCardsOper
     *
     * @mbggenerated
     */
    int countByExample(GeneratedCardsOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GeneratedCardsOper
     *
     * @mbggenerated
     */
    int deleteByExample(GeneratedCardsOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GeneratedCardsOper
     *
     * @mbggenerated
     */
    int insert(GeneratedCardsOper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GeneratedCardsOper
     *
     * @mbggenerated
     */
    int insertSelective(GeneratedCardsOper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GeneratedCardsOper
     *
     * @mbggenerated
     */
    List<GeneratedCardsOper> selectByExample(GeneratedCardsOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GeneratedCardsOper
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GeneratedCardsOper record, @Param("example") GeneratedCardsOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GeneratedCardsOper
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GeneratedCardsOper record, @Param("example") GeneratedCardsOperExample example);
}