package cn.bupt.smartyagl.dao.autogenerate;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.bupt.smartyagl.entity.autogenerate.GoodsRejectedView;
import cn.bupt.smartyagl.entity.autogenerate.GoodsRejectedViewExample;


public interface GoodsRejectedViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejectedView
     *
     * @mbggenerated Thu Sep 08 11:22:21 CST 2016
     */
    int countByExample(GoodsRejectedViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejectedView
     *
     * @mbggenerated Thu Sep 08 11:22:21 CST 2016
     */
    int deleteByExample(GoodsRejectedViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejectedView
     *
     * @mbggenerated Thu Sep 08 11:22:21 CST 2016
     */
    int insert(GoodsRejectedView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejectedView
     *
     * @mbggenerated Thu Sep 08 11:22:21 CST 2016
     */
    int insertSelective(GoodsRejectedView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejectedView
     *
     * @mbggenerated Thu Sep 08 11:22:21 CST 2016
     */
    List<GoodsRejectedView> selectByExample(GoodsRejectedViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejectedView
     *
     * @mbggenerated Thu Sep 08 11:22:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") GoodsRejectedView record, @Param("example") GoodsRejectedViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejectedView
     *
     * @mbggenerated Thu Sep 08 11:22:21 CST 2016
     */
    int updateByExample(@Param("record") GoodsRejectedView record, @Param("example") GoodsRejectedViewExample example);
}