package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.GoodsRejected;
import cn.bupt.smartyagl.entity.autogenerate.GoodsRejectedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsRejectedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejected
     *
     * @mbggenerated
     */
    int countByExample(GoodsRejectedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejected
     *
     * @mbggenerated
     */
    int deleteByExample(GoodsRejectedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejected
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejected
     *
     * @mbggenerated
     */
    int insert(GoodsRejected record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejected
     *
     * @mbggenerated
     */
    int insertSelective(GoodsRejected record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejected
     *
     * @mbggenerated
     */
    List<GoodsRejected> selectByExample(GoodsRejectedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejected
     *
     * @mbggenerated
     */
    GoodsRejected selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejected
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GoodsRejected record, @Param("example") GoodsRejectedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejected
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GoodsRejected record, @Param("example") GoodsRejectedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejected
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsRejected record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsRejected
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsRejected record);
}