package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.GoodsCartView;
import cn.bupt.smartyagl.entity.autogenerate.GoodsCartViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsCartViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GoodsCartView
     *
     * @mbggenerated
     */
    int countByExample(GoodsCartViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GoodsCartView
     *
     * @mbggenerated
     */
    int deleteByExample(GoodsCartViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GoodsCartView
     *
     * @mbggenerated
     */
    int insert(GoodsCartView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GoodsCartView
     *
     * @mbggenerated
     */
    int insertSelective(GoodsCartView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GoodsCartView
     *
     * @mbggenerated
     */
    List<GoodsCartView> selectByExample(GoodsCartViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GoodsCartView
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GoodsCartView record, @Param("example") GoodsCartViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GoodsCartView
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GoodsCartView record, @Param("example") GoodsCartViewExample example);
}