package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.GoodsCart;
import cn.bupt.smartyagl.entity.autogenerate.GoodsCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCart
     *
     * @mbggenerated
     */
    int countByExample(GoodsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCart
     *
     * @mbggenerated
     */
    int deleteByExample(GoodsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCart
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCart
     *
     * @mbggenerated
     */
    int insert(GoodsCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCart
     *
     * @mbggenerated
     */
    int insertSelective(GoodsCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCart
     *
     * @mbggenerated
     */
    List<GoodsCart> selectByExample(GoodsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCart
     *
     * @mbggenerated
     */
    GoodsCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCart
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GoodsCart record, @Param("example") GoodsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCart
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GoodsCart record, @Param("example") GoodsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCart
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCart
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsCart record);
}