package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.GoodsCardLog;
import cn.bupt.smartyagl.entity.autogenerate.GoodsCardLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsCardLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCardLog
     *
     * @mbggenerated
     */
    int countByExample(GoodsCardLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCardLog
     *
     * @mbggenerated
     */
    int deleteByExample(GoodsCardLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCardLog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCardLog
     *
     * @mbggenerated
     */
    int insert(GoodsCardLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCardLog
     *
     * @mbggenerated
     */
    int insertSelective(GoodsCardLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCardLog
     *
     * @mbggenerated
     */
    List<GoodsCardLog> selectByExample(GoodsCardLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCardLog
     *
     * @mbggenerated
     */
    GoodsCardLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCardLog
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GoodsCardLog record, @Param("example") GoodsCardLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCardLog
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GoodsCardLog record, @Param("example") GoodsCardLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCardLog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsCardLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsCardLog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsCardLog record);
}