package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.GoodsSaleStatus;
import cn.bupt.smartyagl.entity.autogenerate.GoodsSaleStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsSaleStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsSaleStatus
     *
     * @mbggenerated
     */
    int countByExample(GoodsSaleStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsSaleStatus
     *
     * @mbggenerated
     */
    int deleteByExample(GoodsSaleStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsSaleStatus
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsSaleStatus
     *
     * @mbggenerated
     */
    int insert(GoodsSaleStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsSaleStatus
     *
     * @mbggenerated
     */
    int insertSelective(GoodsSaleStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsSaleStatus
     *
     * @mbggenerated
     */
    List<GoodsSaleStatus> selectByExample(GoodsSaleStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsSaleStatus
     *
     * @mbggenerated
     */
    GoodsSaleStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsSaleStatus
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GoodsSaleStatus record, @Param("example") GoodsSaleStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsSaleStatus
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GoodsSaleStatus record, @Param("example") GoodsSaleStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsSaleStatus
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsSaleStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsSaleStatus
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsSaleStatus record);
}