package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.GoodsCardLogView;
import cn.bupt.smartyagl.entity.autogenerate.GoodsCardLogViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsCardLogViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GoodsCardLogView
     *
     * @mbggenerated
     */
    int countByExample(GoodsCardLogViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GoodsCardLogView
     *
     * @mbggenerated
     */
    int deleteByExample(GoodsCardLogViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GoodsCardLogView
     *
     * @mbggenerated
     */
    int insert(GoodsCardLogView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GoodsCardLogView
     *
     * @mbggenerated
     */
    int insertSelective(GoodsCardLogView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GoodsCardLogView
     *
     * @mbggenerated
     */
    List<GoodsCardLogView> selectByExample(GoodsCardLogViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GoodsCardLogView
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GoodsCardLogView record, @Param("example") GoodsCardLogViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GoodsCardLogView
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GoodsCardLogView record, @Param("example") GoodsCardLogViewExample example);
}