package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.InputGoods;
import cn.bupt.smartyagl.entity.autogenerate.InputGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InputGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inputGoods
     *
     * @mbggenerated
     */
    int countByExample(InputGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inputGoods
     *
     * @mbggenerated
     */
    int deleteByExample(InputGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inputGoods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inputGoods
     *
     * @mbggenerated
     */
    int insert(InputGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inputGoods
     *
     * @mbggenerated
     */
    int insertSelective(InputGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inputGoods
     *
     * @mbggenerated
     */
    List<InputGoods> selectByExample(InputGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inputGoods
     *
     * @mbggenerated
     */
    InputGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inputGoods
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") InputGoods record, @Param("example") InputGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inputGoods
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") InputGoods record, @Param("example") InputGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inputGoods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InputGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inputGoods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InputGoods record);
}