package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.InputGoodsView;
import cn.bupt.smartyagl.entity.autogenerate.InputGoodsViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InputGoodsViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InputGoodsView
     *
     * @mbggenerated
     */
    int countByExample(InputGoodsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InputGoodsView
     *
     * @mbggenerated
     */
    int deleteByExample(InputGoodsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InputGoodsView
     *
     * @mbggenerated
     */
    int insert(InputGoodsView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InputGoodsView
     *
     * @mbggenerated
     */
    int insertSelective(InputGoodsView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InputGoodsView
     *
     * @mbggenerated
     */
    List<InputGoodsView> selectByExample(InputGoodsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InputGoodsView
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") InputGoodsView record, @Param("example") InputGoodsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InputGoodsView
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") InputGoodsView record, @Param("example") InputGoodsViewExample example);
}