package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.OrderViewWithAdress;
import cn.bupt.smartyagl.entity.autogenerate.OrderViewWithAdressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderViewWithAdressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderViewWithAdress
     *
     * @mbggenerated
     */
    int countByExample(OrderViewWithAdressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderViewWithAdress
     *
     * @mbggenerated
     */
    int deleteByExample(OrderViewWithAdressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderViewWithAdress
     *
     * @mbggenerated
     */
    int insert(OrderViewWithAdress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderViewWithAdress
     *
     * @mbggenerated
     */
    int insertSelective(OrderViewWithAdress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderViewWithAdress
     *
     * @mbggenerated
     */
    List<OrderViewWithAdress> selectByExample(OrderViewWithAdressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderViewWithAdress
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderViewWithAdress record, @Param("example") OrderViewWithAdressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderViewWithAdress
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderViewWithAdress record, @Param("example") OrderViewWithAdressExample example);
}