package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.OrderMaster;
import cn.bupt.smartyagl.entity.autogenerate.OrderMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderMaster
     *
     * @mbggenerated
     */
    int countByExample(OrderMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderMaster
     *
     * @mbggenerated
     */
    int deleteByExample(OrderMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderMaster
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderMaster
     *
     * @mbggenerated
     */
    int insert(OrderMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderMaster
     *
     * @mbggenerated
     */
    int insertSelective(OrderMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderMaster
     *
     * @mbggenerated
     */
    List<OrderMaster> selectByExample(OrderMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderMaster
     *
     * @mbggenerated
     */
    OrderMaster selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderMaster
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderMaster record, @Param("example") OrderMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderMaster
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderMaster record, @Param("example") OrderMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderMaster
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderMaster
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderMaster record);
}