package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.OrderDetailView;
import cn.bupt.smartyagl.entity.autogenerate.OrderDetailViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetailViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderDetailView
     *
     * @mbggenerated
     */
    int countByExample(OrderDetailViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderDetailView
     *
     * @mbggenerated
     */
    int deleteByExample(OrderDetailViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderDetailView
     *
     * @mbggenerated
     */
    int insert(OrderDetailView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderDetailView
     *
     * @mbggenerated
     */
    int insertSelective(OrderDetailView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderDetailView
     *
     * @mbggenerated
     */
    List<OrderDetailView> selectByExample(OrderDetailViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderDetailView
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderDetailView record, @Param("example") OrderDetailViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderDetailView
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderDetailView record, @Param("example") OrderDetailViewExample example);
}