package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.PayLog;
import cn.bupt.smartyagl.entity.autogenerate.PayLogExample;
import cn.bupt.smartyagl.entity.autogenerate.PayLogKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PayLog
     *
     * @mbggenerated
     */
    int countByExample(PayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PayLog
     *
     * @mbggenerated
     */
    int deleteByExample(PayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PayLog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(PayLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PayLog
     *
     * @mbggenerated
     */
    int insert(PayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PayLog
     *
     * @mbggenerated
     */
    int insertSelective(PayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PayLog
     *
     * @mbggenerated
     */
    List<PayLog> selectByExample(PayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PayLog
     *
     * @mbggenerated
     */
    PayLog selectByPrimaryKey(PayLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PayLog
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PayLog record, @Param("example") PayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PayLog
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PayLog record, @Param("example") PayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PayLog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PayLog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayLog record);
}