package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.RecentSearch;
import cn.bupt.smartyagl.entity.autogenerate.RecentSearchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecentSearchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recentSearch
     *
     * @mbggenerated
     */
    int countByExample(RecentSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recentSearch
     *
     * @mbggenerated
     */
    int deleteByExample(RecentSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recentSearch
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recentSearch
     *
     * @mbggenerated
     */
    int insert(RecentSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recentSearch
     *
     * @mbggenerated
     */
    int insertSelective(RecentSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recentSearch
     *
     * @mbggenerated
     */
    List<RecentSearch> selectByExample(RecentSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recentSearch
     *
     * @mbggenerated
     */
    RecentSearch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recentSearch
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RecentSearch record, @Param("example") RecentSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recentSearch
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RecentSearch record, @Param("example") RecentSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recentSearch
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RecentSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recentSearch
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RecentSearch record);
}