package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.RelateBlockManager;
import cn.bupt.smartyagl.entity.autogenerate.RelateBlockManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelateBlockManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relateBlockManager
     *
     * @mbggenerated
     */
    int countByExample(RelateBlockManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relateBlockManager
     *
     * @mbggenerated
     */
    int deleteByExample(RelateBlockManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relateBlockManager
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relateBlockManager
     *
     * @mbggenerated
     */
    int insert(RelateBlockManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relateBlockManager
     *
     * @mbggenerated
     */
    int insertSelective(RelateBlockManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relateBlockManager
     *
     * @mbggenerated
     */
    List<RelateBlockManager> selectByExample(RelateBlockManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relateBlockManager
     *
     * @mbggenerated
     */
    RelateBlockManager selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relateBlockManager
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RelateBlockManager record, @Param("example") RelateBlockManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relateBlockManager
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RelateBlockManager record, @Param("example") RelateBlockManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relateBlockManager
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RelateBlockManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relateBlockManager
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RelateBlockManager record);
}