package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.UserAuthView;
import cn.bupt.smartyagl.entity.autogenerate.UserAuthViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAuthViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserAuthView
     *
     * @mbggenerated
     */
    int countByExample(UserAuthViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserAuthView
     *
     * @mbggenerated
     */
    int deleteByExample(UserAuthViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserAuthView
     *
     * @mbggenerated
     */
    int insert(UserAuthView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserAuthView
     *
     * @mbggenerated
     */
    int insertSelective(UserAuthView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserAuthView
     *
     * @mbggenerated
     */
    List<UserAuthView> selectByExample(UserAuthViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserAuthView
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserAuthView record, @Param("example") UserAuthViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserAuthView
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserAuthView record, @Param("example") UserAuthViewExample example);
}