package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.Users_copy;
import cn.bupt.smartyagl.entity.autogenerate.Users_copyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Users_copyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_copy
     *
     * @mbggenerated
     */
    int countByExample(Users_copyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_copy
     *
     * @mbggenerated
     */
    int deleteByExample(Users_copyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_copy
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_copy
     *
     * @mbggenerated
     */
    int insert(Users_copy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_copy
     *
     * @mbggenerated
     */
    int insertSelective(Users_copy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_copy
     *
     * @mbggenerated
     */
    List<Users_copy> selectByExample(Users_copyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_copy
     *
     * @mbggenerated
     */
    Users_copy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_copy
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Users_copy record, @Param("example") Users_copyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_copy
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Users_copy record, @Param("example") Users_copyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_copy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Users_copy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_copy
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Users_copy record);
}