package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.QRCodeRecode;
import cn.bupt.smartyagl.entity.autogenerate.QRCodeRecodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QRCodeRecodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCodeRecode
     *
     * @mbggenerated
     */
    int countByExample(QRCodeRecodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCodeRecode
     *
     * @mbggenerated
     */
    int deleteByExample(QRCodeRecodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCodeRecode
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCodeRecode
     *
     * @mbggenerated
     */
    int insert(QRCodeRecode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCodeRecode
     *
     * @mbggenerated
     */
    int insertSelective(QRCodeRecode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCodeRecode
     *
     * @mbggenerated
     */
    List<QRCodeRecode> selectByExample(QRCodeRecodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCodeRecode
     *
     * @mbggenerated
     */
    QRCodeRecode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCodeRecode
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QRCodeRecode record, @Param("example") QRCodeRecodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCodeRecode
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QRCodeRecode record, @Param("example") QRCodeRecodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCodeRecode
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QRCodeRecode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCodeRecode
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QRCodeRecode record);
}