package cn.bupt.smartyagl.entity.autogenerate;

public class LikeGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LikeGoods.id
     *
     * @mbggenerated Sat Jun 04 14:25:43 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LikeGoods.userId
     *
     * @mbggenerated Sat Jun 04 14:25:43 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LikeGoods.goodsId
     *
     * @mbggenerated Sat Jun 04 14:25:43 CST 2016
     */
    private Integer goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.id
     *
     * @return the value of LikeGoods.id
     *
     * @mbggenerated Sat Jun 04 14:25:43 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.id
     *
     * @param id the value for LikeGoods.id
     *
     * @mbggenerated Sat Jun 04 14:25:43 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.userId
     *
     * @return the value of LikeGoods.userId
     *
     * @mbggenerated Sat Jun 04 14:25:43 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.userId
     *
     * @param userId the value for LikeGoods.userId
     *
     * @mbggenerated Sat Jun 04 14:25:43 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.goodsId
     *
     * @return the value of LikeGoods.goodsId
     *
     * @mbggenerated Sat Jun 04 14:25:43 CST 2016
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.goodsId
     *
     * @param goodsId the value for LikeGoods.goodsId
     *
     * @mbggenerated Sat Jun 04 14:25:43 CST 2016
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }
}