package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.FarmVisitOrderView;
import cn.bupt.smartyagl.entity.autogenerate.FarmVisitOrderViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FarmVisitOrderViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisitOrderView
     *
     * @mbggenerated
     */
    int countByExample(FarmVisitOrderViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisitOrderView
     *
     * @mbggenerated
     */
    int deleteByExample(FarmVisitOrderViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisitOrderView
     *
     * @mbggenerated
     */
    int insert(FarmVisitOrderView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisitOrderView
     *
     * @mbggenerated
     */
    int insertSelective(FarmVisitOrderView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisitOrderView
     *
     * @mbggenerated
     */
    List<FarmVisitOrderView> selectByExample(FarmVisitOrderViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisitOrderView
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FarmVisitOrderView record, @Param("example") FarmVisitOrderViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmVisitOrderView
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FarmVisitOrderView record, @Param("example") FarmVisitOrderViewExample example);
}