package cn.bupt.smartyagl.dao.autogenerate;

import cn.bupt.smartyagl.entity.autogenerate.HasBuyRecordGoodsCard;
import cn.bupt.smartyagl.entity.autogenerate.HasBuyRecordGoodsCardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HasBuyRecordGoodsCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hasBuyRecordGoodsCard
     *
     * @mbggenerated
     */
    int countByExample(HasBuyRecordGoodsCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hasBuyRecordGoodsCard
     *
     * @mbggenerated
     */
    int deleteByExample(HasBuyRecordGoodsCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hasBuyRecordGoodsCard
     *
     * @mbggenerated
     */
    int insert(HasBuyRecordGoodsCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hasBuyRecordGoodsCard
     *
     * @mbggenerated
     */
    int insertSelective(HasBuyRecordGoodsCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hasBuyRecordGoodsCard
     *
     * @mbggenerated
     */
    List<HasBuyRecordGoodsCard> selectByExample(HasBuyRecordGoodsCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hasBuyRecordGoodsCard
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HasBuyRecordGoodsCard record, @Param("example") HasBuyRecordGoodsCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hasBuyRecordGoodsCard
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HasBuyRecordGoodsCard record, @Param("example") HasBuyRecordGoodsCardExample example);
}