package cn.bupt.smartyagl.entity.autogenerate;

import java.util.Date;

public class Album {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.photoName
     *
     * @mbggenerated
     */
    private String photoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.pictures
     *
     * @mbggenerated
     */
    private String pictures;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.ratio
     *
     * @mbggenerated
     */
    private Float ratio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.creatTime
     *
     * @mbggenerated
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.top
     *
     * @mbggenerated
     */
    private Integer top;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.parentId
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.id
     *
     * @return the value of album.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.id
     *
     * @param id the value for album.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.photoName
     *
     * @return the value of album.photoName
     *
     * @mbggenerated
     */
    public String getPhotoName() {
        return photoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.photoName
     *
     * @param photoName the value for album.photoName
     *
     * @mbggenerated
     */
    public void setPhotoName(String photoName) {
        this.photoName = photoName == null ? null : photoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.pictures
     *
     * @return the value of album.pictures
     *
     * @mbggenerated
     */
    public String getPictures() {
        return pictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.pictures
     *
     * @param pictures the value for album.pictures
     *
     * @mbggenerated
     */
    public void setPictures(String pictures) {
        this.pictures = pictures == null ? null : pictures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.ratio
     *
     * @return the value of album.ratio
     *
     * @mbggenerated
     */
    public Float getRatio() {
        return ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.ratio
     *
     * @param d the value for album.ratio
     *
     * @mbggenerated
     */
    public void setRatio(float d) {
        this.ratio = d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.creatTime
     *
     * @return the value of album.creatTime
     *
     * @mbggenerated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.creatTime
     *
     * @param creatTime the value for album.creatTime
     *
     * @mbggenerated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.status
     *
     * @return the value of album.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.status
     *
     * @param status the value for album.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.top
     *
     * @return the value of album.top
     *
     * @mbggenerated
     */
    public Integer getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.top
     *
     * @param top the value for album.top
     *
     * @mbggenerated
     */
    public void setTop(Integer top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.parentId
     *
     * @return the value of album.parentId
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.parentId
     *
     * @param parentId the value for album.parentId
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}