package cn.bupt.smartyagl.entity.autogenerate;

public class Camera {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera.port
     *
     * @mbggenerated
     */
    private String port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera.passwd
     *
     * @mbggenerated
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera.device_port
     *
     * @mbggenerated
     */
    private String device_port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera.is_top
     *
     * @mbggenerated
     */
    private Integer is_top;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera.id
     *
     * @return the value of camera.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera.id
     *
     * @param id the value for camera.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera.title
     *
     * @return the value of camera.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera.title
     *
     * @param title the value for camera.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera.ip
     *
     * @return the value of camera.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera.ip
     *
     * @param ip the value for camera.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera.port
     *
     * @return the value of camera.port
     *
     * @mbggenerated
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera.port
     *
     * @param port the value for camera.port
     *
     * @mbggenerated
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera.name
     *
     * @return the value of camera.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera.name
     *
     * @param name the value for camera.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera.passwd
     *
     * @return the value of camera.passwd
     *
     * @mbggenerated
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera.passwd
     *
     * @param passwd the value for camera.passwd
     *
     * @mbggenerated
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera.device_port
     *
     * @return the value of camera.device_port
     *
     * @mbggenerated
     */
    public String getDevice_port() {
        return device_port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera.device_port
     *
     * @param device_port the value for camera.device_port
     *
     * @mbggenerated
     */
    public void setDevice_port(String device_port) {
        this.device_port = device_port == null ? null : device_port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera.is_top
     *
     * @return the value of camera.is_top
     *
     * @mbggenerated
     */
    public Integer getIs_top() {
        return is_top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera.is_top
     *
     * @param is_top the value for camera.is_top
     *
     * @mbggenerated
     */
    public void setIs_top(Integer is_top) {
        this.is_top = is_top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera.status
     *
     * @return the value of camera.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera.status
     *
     * @param status the value for camera.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}