package cn.bupt.smartyagl.entity.autogenerate;

public class CollectView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CollectView.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CollectView.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CollectView.goodsId
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CollectView.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CollectView.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CollectView.stock
     *
     * @mbggenerated
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CollectView.picture
     *
     * @mbggenerated
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CollectView.typeIdParent
     *
     * @mbggenerated
     */
    private Integer typeIdParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CollectView.typeIdChild
     *
     * @mbggenerated
     */
    private Integer typeIdChild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CollectView.typeParent
     *
     * @mbggenerated
     */
    private String typeParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CollectView.typeChild
     *
     * @mbggenerated
     */
    private String typeChild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CollectView.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CollectView.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CollectView.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CollectView.specialPrice
     *
     * @mbggenerated
     */
    private Double specialPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CollectView.saleStatus
     *
     * @mbggenerated
     */
    private Integer saleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CollectView.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CollectView.id
     *
     * @return the value of CollectView.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CollectView.id
     *
     * @param id the value for CollectView.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CollectView.userId
     *
     * @return the value of CollectView.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CollectView.userId
     *
     * @param userId the value for CollectView.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CollectView.goodsId
     *
     * @return the value of CollectView.goodsId
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CollectView.goodsId
     *
     * @param goodsId the value for CollectView.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CollectView.price
     *
     * @return the value of CollectView.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CollectView.price
     *
     * @param price the value for CollectView.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CollectView.score
     *
     * @return the value of CollectView.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CollectView.score
     *
     * @param score the value for CollectView.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CollectView.stock
     *
     * @return the value of CollectView.stock
     *
     * @mbggenerated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CollectView.stock
     *
     * @param stock the value for CollectView.stock
     *
     * @mbggenerated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CollectView.picture
     *
     * @return the value of CollectView.picture
     *
     * @mbggenerated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CollectView.picture
     *
     * @param picture the value for CollectView.picture
     *
     * @mbggenerated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CollectView.typeIdParent
     *
     * @return the value of CollectView.typeIdParent
     *
     * @mbggenerated
     */
    public Integer getTypeIdParent() {
        return typeIdParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CollectView.typeIdParent
     *
     * @param typeIdParent the value for CollectView.typeIdParent
     *
     * @mbggenerated
     */
    public void setTypeIdParent(Integer typeIdParent) {
        this.typeIdParent = typeIdParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CollectView.typeIdChild
     *
     * @return the value of CollectView.typeIdChild
     *
     * @mbggenerated
     */
    public Integer getTypeIdChild() {
        return typeIdChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CollectView.typeIdChild
     *
     * @param typeIdChild the value for CollectView.typeIdChild
     *
     * @mbggenerated
     */
    public void setTypeIdChild(Integer typeIdChild) {
        this.typeIdChild = typeIdChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CollectView.typeParent
     *
     * @return the value of CollectView.typeParent
     *
     * @mbggenerated
     */
    public String getTypeParent() {
        return typeParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CollectView.typeParent
     *
     * @param typeParent the value for CollectView.typeParent
     *
     * @mbggenerated
     */
    public void setTypeParent(String typeParent) {
        this.typeParent = typeParent == null ? null : typeParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CollectView.typeChild
     *
     * @return the value of CollectView.typeChild
     *
     * @mbggenerated
     */
    public String getTypeChild() {
        return typeChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CollectView.typeChild
     *
     * @param typeChild the value for CollectView.typeChild
     *
     * @mbggenerated
     */
    public void setTypeChild(String typeChild) {
        this.typeChild = typeChild == null ? null : typeChild.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CollectView.name
     *
     * @return the value of CollectView.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CollectView.name
     *
     * @param name the value for CollectView.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CollectView.title
     *
     * @return the value of CollectView.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CollectView.title
     *
     * @param title the value for CollectView.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CollectView.unit
     *
     * @return the value of CollectView.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CollectView.unit
     *
     * @param unit the value for CollectView.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CollectView.specialPrice
     *
     * @return the value of CollectView.specialPrice
     *
     * @mbggenerated
     */
    public Double getSpecialPrice() {
        return specialPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CollectView.specialPrice
     *
     * @param specialPrice the value for CollectView.specialPrice
     *
     * @mbggenerated
     */
    public void setSpecialPrice(Double specialPrice) {
        this.specialPrice = specialPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CollectView.saleStatus
     *
     * @return the value of CollectView.saleStatus
     *
     * @mbggenerated
     */
    public Integer getSaleStatus() {
        return saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CollectView.saleStatus
     *
     * @param saleStatus the value for CollectView.saleStatus
     *
     * @mbggenerated
     */
    public void setSaleStatus(Integer saleStatus) {
        this.saleStatus = saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CollectView.status
     *
     * @return the value of CollectView.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CollectView.status
     *
     * @param status the value for CollectView.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}