package cn.bupt.smartyagl.entity.autogenerate;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.goodsId
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.parentMessageId
     *
     * @mbggenerated
     */
    private Integer parentMessageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.pictureList
     *
     * @mbggenerated
     */
    private String pictureList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.isAnonymous
     *
     * @mbggenerated
     */
    private Integer isAnonymous;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.viewNum
     *
     * @mbggenerated
     */
    private Integer viewNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.userId
     *
     * @return the value of comment.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.userId
     *
     * @param userId the value for comment.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.goodsId
     *
     * @return the value of comment.goodsId
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.goodsId
     *
     * @param goodsId the value for comment.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.parentMessageId
     *
     * @return the value of comment.parentMessageId
     *
     * @mbggenerated
     */
    public Integer getParentMessageId() {
        return parentMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.parentMessageId
     *
     * @param parentMessageId the value for comment.parentMessageId
     *
     * @mbggenerated
     */
    public void setParentMessageId(Integer parentMessageId) {
        this.parentMessageId = parentMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.pictureList
     *
     * @return the value of comment.pictureList
     *
     * @mbggenerated
     */
    public String getPictureList() {
        return pictureList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.pictureList
     *
     * @param pictureList the value for comment.pictureList
     *
     * @mbggenerated
     */
    public void setPictureList(String pictureList) {
        this.pictureList = pictureList == null ? null : pictureList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.level
     *
     * @return the value of comment.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.level
     *
     * @param level the value for comment.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.createTime
     *
     * @return the value of comment.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.createTime
     *
     * @param createTime the value for comment.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.isAnonymous
     *
     * @return the value of comment.isAnonymous
     *
     * @mbggenerated
     */
    public Integer getIsAnonymous() {
        return isAnonymous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.isAnonymous
     *
     * @param isAnonymous the value for comment.isAnonymous
     *
     * @mbggenerated
     */
    public void setIsAnonymous(Integer isAnonymous) {
        this.isAnonymous = isAnonymous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.viewNum
     *
     * @return the value of comment.viewNum
     *
     * @mbggenerated
     */
    public Integer getViewNum() {
        return viewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.viewNum
     *
     * @param viewNum the value for comment.viewNum
     *
     * @mbggenerated
     */
    public void setViewNum(Integer viewNum) {
        this.viewNum = viewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.status
     *
     * @return the value of comment.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.status
     *
     * @param status the value for comment.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}