package cn.bupt.smartyagl.entity.autogenerate;

import java.util.Date;

public class FarmMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmMessage.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmMessage.subTitle
     *
     * @mbggenerated
     */
    private String subTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmMessage.messageName
     *
     * @mbggenerated
     */
    private String messageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmMessage.messageType
     *
     * @mbggenerated
     */
    private Integer messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmMessage.creatTime
     *
     * @mbggenerated
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmMessage.updateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmMessage.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmMessage.topOrNot
     *
     * @mbggenerated
     */
    private Integer topOrNot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmMessage.originalMessageId
     *
     * @mbggenerated
     */
    private Integer originalMessageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmMessage.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmMessage.picture
     *
     * @mbggenerated
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmMessage.currentMessage
     *
     * @mbggenerated
     */
    private String currentMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmMessage.id
     *
     * @return the value of farmMessage.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmMessage.id
     *
     * @param id the value for farmMessage.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmMessage.subTitle
     *
     * @return the value of farmMessage.subTitle
     *
     * @mbggenerated
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmMessage.subTitle
     *
     * @param subTitle the value for farmMessage.subTitle
     *
     * @mbggenerated
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle == null ? null : subTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmMessage.messageName
     *
     * @return the value of farmMessage.messageName
     *
     * @mbggenerated
     */
    public String getMessageName() {
        return messageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmMessage.messageName
     *
     * @param messageName the value for farmMessage.messageName
     *
     * @mbggenerated
     */
    public void setMessageName(String messageName) {
        this.messageName = messageName == null ? null : messageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmMessage.messageType
     *
     * @return the value of farmMessage.messageType
     *
     * @mbggenerated
     */
    public Integer getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmMessage.messageType
     *
     * @param messageType the value for farmMessage.messageType
     *
     * @mbggenerated
     */
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmMessage.creatTime
     *
     * @return the value of farmMessage.creatTime
     *
     * @mbggenerated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmMessage.creatTime
     *
     * @param creatTime the value for farmMessage.creatTime
     *
     * @mbggenerated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmMessage.updateTime
     *
     * @return the value of farmMessage.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmMessage.updateTime
     *
     * @param updateTime the value for farmMessage.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmMessage.status
     *
     * @return the value of farmMessage.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmMessage.status
     *
     * @param status the value for farmMessage.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmMessage.topOrNot
     *
     * @return the value of farmMessage.topOrNot
     *
     * @mbggenerated
     */
    public Integer getTopOrNot() {
        return topOrNot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmMessage.topOrNot
     *
     * @param topOrNot the value for farmMessage.topOrNot
     *
     * @mbggenerated
     */
    public void setTopOrNot(Integer topOrNot) {
        this.topOrNot = topOrNot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmMessage.originalMessageId
     *
     * @return the value of farmMessage.originalMessageId
     *
     * @mbggenerated
     */
    public Integer getOriginalMessageId() {
        return originalMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmMessage.originalMessageId
     *
     * @param originalMessageId the value for farmMessage.originalMessageId
     *
     * @mbggenerated
     */
    public void setOriginalMessageId(Integer originalMessageId) {
        this.originalMessageId = originalMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmMessage.icon
     *
     * @return the value of farmMessage.icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmMessage.icon
     *
     * @param icon the value for farmMessage.icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmMessage.picture
     *
     * @return the value of farmMessage.picture
     *
     * @mbggenerated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmMessage.picture
     *
     * @param picture the value for farmMessage.picture
     *
     * @mbggenerated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmMessage.currentMessage
     *
     * @return the value of farmMessage.currentMessage
     *
     * @mbggenerated
     */
    public String getCurrentMessage() {
        return currentMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmMessage.currentMessage
     *
     * @param currentMessage the value for farmMessage.currentMessage
     *
     * @mbggenerated
     */
    public void setCurrentMessage(String currentMessage) {
        this.currentMessage = currentMessage == null ? null : currentMessage.trim();
    }
}