package cn.bupt.smartyagl.entity.autogenerate;

public class Freight {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight.money
     *
     * @mbggenerated
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight.goodsId
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight.isdisplay
     *
     * @mbggenerated
     */
    private Integer isdisplay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight.auditStatus
     *
     * @mbggenerated
     */
    private Integer auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight.sourceId
     *
     * @mbggenerated
     */
    private Integer sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight.weight
     *
     * @mbggenerated
     */
    private Double weight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight.id
     *
     * @return the value of freight.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight.id
     *
     * @param id the value for freight.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight.money
     *
     * @return the value of freight.money
     *
     * @mbggenerated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight.money
     *
     * @param money the value for freight.money
     *
     * @mbggenerated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight.province
     *
     * @return the value of freight.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight.province
     *
     * @param province the value for freight.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight.city
     *
     * @return the value of freight.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight.city
     *
     * @param city the value for freight.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight.goodsId
     *
     * @return the value of freight.goodsId
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight.goodsId
     *
     * @param goodsId the value for freight.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight.isdisplay
     *
     * @return the value of freight.isdisplay
     *
     * @mbggenerated
     */
    public Integer getIsdisplay() {
        return isdisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight.isdisplay
     *
     * @param isdisplay the value for freight.isdisplay
     *
     * @mbggenerated
     */
    public void setIsdisplay(Integer isdisplay) {
        this.isdisplay = isdisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight.auditStatus
     *
     * @return the value of freight.auditStatus
     *
     * @mbggenerated
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight.auditStatus
     *
     * @param auditStatus the value for freight.auditStatus
     *
     * @mbggenerated
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight.sourceId
     *
     * @return the value of freight.sourceId
     *
     * @mbggenerated
     */
    public Integer getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight.sourceId
     *
     * @param sourceId the value for freight.sourceId
     *
     * @mbggenerated
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight.weight
     *
     * @return the value of freight.weight
     *
     * @mbggenerated
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight.weight
     *
     * @param weight the value for freight.weight
     *
     * @mbggenerated
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }
}