package cn.bupt.smartyagl.entity.autogenerate;

import java.util.Date;

public class GeneratedCards {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generatedCards.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generatedCards.oper_time
     *
     * @mbggenerated
     */
    private Date oper_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generatedCards.denomination
     *
     * @mbggenerated
     */
    private Double denomination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generatedCards.cardNum
     *
     * @mbggenerated
     */
    private Integer cardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generatedCards.operator
     *
     * @mbggenerated
     */
    private Integer operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generatedCards.reviewed
     *
     * @mbggenerated
     */
    private Boolean reviewed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generatedCards.id
     *
     * @return the value of generatedCards.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generatedCards.id
     *
     * @param id the value for generatedCards.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generatedCards.oper_time
     *
     * @return the value of generatedCards.oper_time
     *
     * @mbggenerated
     */
    public Date getOper_time() {
        return oper_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generatedCards.oper_time
     *
     * @param oper_time the value for generatedCards.oper_time
     *
     * @mbggenerated
     */
    public void setOper_time(Date oper_time) {
        this.oper_time = oper_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generatedCards.denomination
     *
     * @return the value of generatedCards.denomination
     *
     * @mbggenerated
     */
    public Double getDenomination() {
        return denomination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generatedCards.denomination
     *
     * @param denomination the value for generatedCards.denomination
     *
     * @mbggenerated
     */
    public void setDenomination(Double denomination) {
        this.denomination = denomination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generatedCards.cardNum
     *
     * @return the value of generatedCards.cardNum
     *
     * @mbggenerated
     */
    public Integer getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generatedCards.cardNum
     *
     * @param cardNum the value for generatedCards.cardNum
     *
     * @mbggenerated
     */
    public void setCardNum(Integer cardNum) {
        this.cardNum = cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generatedCards.operator
     *
     * @return the value of generatedCards.operator
     *
     * @mbggenerated
     */
    public Integer getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generatedCards.operator
     *
     * @param operator the value for generatedCards.operator
     *
     * @mbggenerated
     */
    public void setOperator(Integer operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generatedCards.reviewed
     *
     * @return the value of generatedCards.reviewed
     *
     * @mbggenerated
     */
    public Boolean getReviewed() {
        return reviewed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generatedCards.reviewed
     *
     * @param reviewed the value for generatedCards.reviewed
     *
     * @mbggenerated
     */
    public void setReviewed(Boolean reviewed) {
        this.reviewed = reviewed;
    }
}