package cn.bupt.smartyagl.entity.autogenerate;

import java.util.Date;

public class GoodsRejected {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsRejected.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsRejected.orderId
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsRejected.rejectedTime
     *
     * @mbggenerated
     */
    private Date rejectedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsRejected.id
     *
     * @return the value of goodsRejected.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsRejected.id
     *
     * @param id the value for goodsRejected.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsRejected.orderId
     *
     * @return the value of goodsRejected.orderId
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsRejected.orderId
     *
     * @param orderId the value for goodsRejected.orderId
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsRejected.rejectedTime
     *
     * @return the value of goodsRejected.rejectedTime
     *
     * @mbggenerated
     */
    public Date getRejectedTime() {
        return rejectedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsRejected.rejectedTime
     *
     * @param rejectedTime the value for goodsRejected.rejectedTime
     *
     * @mbggenerated
     */
    public void setRejectedTime(Date rejectedTime) {
        this.rejectedTime = rejectedTime;
    }
}