package cn.bupt.smartyagl.entity.autogenerate;

import java.util.Date;

public class InputGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inputGoods.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inputGoods.goods_id
     *
     * @mbggenerated
     */
    private Integer goods_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inputGoods.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inputGoods.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inputGoods.add_time
     *
     * @mbggenerated
     */
    private Date add_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inputGoods.id
     *
     * @return the value of inputGoods.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inputGoods.id
     *
     * @param id the value for inputGoods.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inputGoods.goods_id
     *
     * @return the value of inputGoods.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoods_id() {
        return goods_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inputGoods.goods_id
     *
     * @param goods_id the value for inputGoods.goods_id
     *
     * @mbggenerated
     */
    public void setGoods_id(Integer goods_id) {
        this.goods_id = goods_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inputGoods.num
     *
     * @return the value of inputGoods.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inputGoods.num
     *
     * @param num the value for inputGoods.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inputGoods.status
     *
     * @return the value of inputGoods.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inputGoods.status
     *
     * @param status the value for inputGoods.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inputGoods.add_time
     *
     * @return the value of inputGoods.add_time
     *
     * @mbggenerated
     */
    public Date getAdd_time() {
        return add_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inputGoods.add_time
     *
     * @param add_time the value for inputGoods.add_time
     *
     * @mbggenerated
     */
    public void setAdd_time(Date add_time) {
        this.add_time = add_time;
    }
}