package cn.bupt.smartyagl.entity.autogenerate;

import java.util.Date;

public class OrderDetailView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetailView.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetailView.goodsId
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetailView.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetailView.buyTime
     *
     * @mbggenerated
     */
    private Date buyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetailView.typeIdParent
     *
     * @mbggenerated
     */
    private Integer typeIdParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetailView.picture
     *
     * @mbggenerated
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetailView.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetailView.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetailView.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetailView.specialPrice
     *
     * @mbggenerated
     */
    private Double specialPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetailView.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetailView.typeIdChild
     *
     * @mbggenerated
     */
    private Integer typeIdChild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetailView.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderDetailView.saleStatus
     *
     * @mbggenerated
     */
    private Integer saleStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetailView.id
     *
     * @return the value of OrderDetailView.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetailView.id
     *
     * @param id the value for OrderDetailView.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetailView.goodsId
     *
     * @return the value of OrderDetailView.goodsId
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetailView.goodsId
     *
     * @param goodsId the value for OrderDetailView.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetailView.num
     *
     * @return the value of OrderDetailView.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetailView.num
     *
     * @param num the value for OrderDetailView.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetailView.buyTime
     *
     * @return the value of OrderDetailView.buyTime
     *
     * @mbggenerated
     */
    public Date getBuyTime() {
        return buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetailView.buyTime
     *
     * @param buyTime the value for OrderDetailView.buyTime
     *
     * @mbggenerated
     */
    public void setBuyTime(Date buyTime) {
        this.buyTime = buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetailView.typeIdParent
     *
     * @return the value of OrderDetailView.typeIdParent
     *
     * @mbggenerated
     */
    public Integer getTypeIdParent() {
        return typeIdParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetailView.typeIdParent
     *
     * @param typeIdParent the value for OrderDetailView.typeIdParent
     *
     * @mbggenerated
     */
    public void setTypeIdParent(Integer typeIdParent) {
        this.typeIdParent = typeIdParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetailView.picture
     *
     * @return the value of OrderDetailView.picture
     *
     * @mbggenerated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetailView.picture
     *
     * @param picture the value for OrderDetailView.picture
     *
     * @mbggenerated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetailView.name
     *
     * @return the value of OrderDetailView.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetailView.name
     *
     * @param name the value for OrderDetailView.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetailView.title
     *
     * @return the value of OrderDetailView.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetailView.title
     *
     * @param title the value for OrderDetailView.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetailView.price
     *
     * @return the value of OrderDetailView.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetailView.price
     *
     * @param price the value for OrderDetailView.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetailView.specialPrice
     *
     * @return the value of OrderDetailView.specialPrice
     *
     * @mbggenerated
     */
    public Double getSpecialPrice() {
        return specialPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetailView.specialPrice
     *
     * @param specialPrice the value for OrderDetailView.specialPrice
     *
     * @mbggenerated
     */
    public void setSpecialPrice(Double specialPrice) {
        this.specialPrice = specialPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetailView.unit
     *
     * @return the value of OrderDetailView.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetailView.unit
     *
     * @param unit the value for OrderDetailView.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetailView.typeIdChild
     *
     * @return the value of OrderDetailView.typeIdChild
     *
     * @mbggenerated
     */
    public Integer getTypeIdChild() {
        return typeIdChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetailView.typeIdChild
     *
     * @param typeIdChild the value for OrderDetailView.typeIdChild
     *
     * @mbggenerated
     */
    public void setTypeIdChild(Integer typeIdChild) {
        this.typeIdChild = typeIdChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetailView.score
     *
     * @return the value of OrderDetailView.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetailView.score
     *
     * @param score the value for OrderDetailView.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderDetailView.saleStatus
     *
     * @return the value of OrderDetailView.saleStatus
     *
     * @mbggenerated
     */
    public Integer getSaleStatus() {
        return saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderDetailView.saleStatus
     *
     * @param saleStatus the value for OrderDetailView.saleStatus
     *
     * @mbggenerated
     */
    public void setSaleStatus(Integer saleStatus) {
        this.saleStatus = saleStatus;
    }
}