package cn.bupt.smartyagl.entity.autogenerate;

import java.math.BigDecimal;
import java.util.Date;

public class OrderMaster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderMaster.orderId
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderMaster.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderMaster.addressId
     *
     * @mbggenerated
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderMaster.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderMaster.freight
     *
     * @mbggenerated
     */
    private BigDecimal freight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderMaster.message
     *
     * @mbggenerated
     */
    private String message = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderMaster.status
     *
     * @mbggenerated
     */
    private Integer status = 1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderMaster.buyTime
     *
     * @mbggenerated
     */
    private Date buyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderMaster.tracking
     *
     * @mbggenerated
     */
    private String tracking="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderMaster.is_show
     *
     * @mbggenerated
     */
    private Integer is_show = 1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderMaster.pick_up
     *
     * @mbggenerated
     */
    private Integer pick_up;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderMaster.share_id
     *
     * @mbggenerated
     */
    private Integer share_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderMaster.isDelete
     *
     * @mbggenerated
     */
    private Boolean isDelete = false;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderMaster.orderId
     *
     * @return the value of orderMaster.orderId
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderMaster.orderId
     *
     * @param orderId the value for orderMaster.orderId
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderMaster.userId
     *
     * @return the value of orderMaster.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderMaster.userId
     *
     * @param userId the value for orderMaster.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderMaster.addressId
     *
     * @return the value of orderMaster.addressId
     *
     * @mbggenerated
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderMaster.addressId
     *
     * @param addressId the value for orderMaster.addressId
     *
     * @mbggenerated
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderMaster.amount
     *
     * @return the value of orderMaster.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderMaster.amount
     *
     * @param amount the value for orderMaster.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderMaster.freight
     *
     * @return the value of orderMaster.freight
     *
     * @mbggenerated
     */
    public BigDecimal getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderMaster.freight
     *
     * @param freight the value for orderMaster.freight
     *
     * @mbggenerated
     */
    public void setFreight(BigDecimal freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderMaster.message
     *
     * @return the value of orderMaster.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderMaster.message
     *
     * @param message the value for orderMaster.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderMaster.status
     *
     * @return the value of orderMaster.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderMaster.status
     *
     * @param status the value for orderMaster.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderMaster.buyTime
     *
     * @return the value of orderMaster.buyTime
     *
     * @mbggenerated
     */
    public Date getBuyTime() {
        return buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderMaster.buyTime
     *
     * @param buyTime the value for orderMaster.buyTime
     *
     * @mbggenerated
     */
    public void setBuyTime(Date buyTime) {
        this.buyTime = buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderMaster.tracking
     *
     * @return the value of orderMaster.tracking
     *
     * @mbggenerated
     */
    public String getTracking() {
        return tracking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderMaster.tracking
     *
     * @param tracking the value for orderMaster.tracking
     *
     * @mbggenerated
     */
    public void setTracking(String tracking) {
        this.tracking = tracking == null ? null : tracking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderMaster.is_show
     *
     * @return the value of orderMaster.is_show
     *
     * @mbggenerated
     */
    public Integer getIs_show() {
        return is_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderMaster.is_show
     *
     * @param is_show the value for orderMaster.is_show
     *
     * @mbggenerated
     */
    public void setIs_show(Integer is_show) {
        this.is_show = is_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderMaster.pick_up
     *
     * @return the value of orderMaster.pick_up
     *
     * @mbggenerated
     */
    public Integer getPick_up() {
        return pick_up;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderMaster.pick_up
     *
     * @param pick_up the value for orderMaster.pick_up
     *
     * @mbggenerated
     */
    public void setPick_up(Integer pick_up) {
        this.pick_up = pick_up;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderMaster.share_id
     *
     * @return the value of orderMaster.share_id
     *
     * @mbggenerated
     */
    public Integer getShare_id() {
        return share_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderMaster.share_id
     *
     * @param share_id the value for orderMaster.share_id
     *
     * @mbggenerated
     */
    public void setShare_id(Integer share_id) {
        this.share_id = share_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderMaster.isDelete
     *
     * @return the value of orderMaster.isDelete
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderMaster.isDelete
     *
     * @param isDelete the value for orderMaster.isDelete
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}