package cn.bupt.smartyagl.entity.autogenerate;

import java.util.Date;

public class OrderList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.addressId
     *
     * @mbggenerated
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.goodsId
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.money
     *
     * @mbggenerated
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.freight
     *
     * @mbggenerated
     */
    private Double freight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.buyTime
     *
     * @mbggenerated
     */
    private Date buyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.tracking
     *
     * @mbggenerated
     */
    private String tracking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.is_show
     *
     * @mbggenerated
     */
    private Integer is_show;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.pick_up
     *
     * @mbggenerated
     */
    private Integer pick_up;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.sharer_id
     *
     * @mbggenerated
     */
    private Integer sharer_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderList.isDelete
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.id
     *
     * @return the value of orderList.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.id
     *
     * @param id the value for orderList.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.userId
     *
     * @return the value of orderList.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.userId
     *
     * @param userId the value for orderList.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.addressId
     *
     * @return the value of orderList.addressId
     *
     * @mbggenerated
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.addressId
     *
     * @param addressId the value for orderList.addressId
     *
     * @mbggenerated
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.goodsId
     *
     * @return the value of orderList.goodsId
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.goodsId
     *
     * @param goodsId the value for orderList.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.num
     *
     * @return the value of orderList.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.num
     *
     * @param num the value for orderList.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.money
     *
     * @return the value of orderList.money
     *
     * @mbggenerated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.money
     *
     * @param money the value for orderList.money
     *
     * @mbggenerated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.freight
     *
     * @return the value of orderList.freight
     *
     * @mbggenerated
     */
    public Double getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.freight
     *
     * @param freight the value for orderList.freight
     *
     * @mbggenerated
     */
    public void setFreight(Double freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.message
     *
     * @return the value of orderList.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.message
     *
     * @param message the value for orderList.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.status
     *
     * @return the value of orderList.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.status
     *
     * @param status the value for orderList.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.buyTime
     *
     * @return the value of orderList.buyTime
     *
     * @mbggenerated
     */
    public Date getBuyTime() {
        return buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.buyTime
     *
     * @param buyTime the value for orderList.buyTime
     *
     * @mbggenerated
     */
    public void setBuyTime(Date buyTime) {
        this.buyTime = buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.tracking
     *
     * @return the value of orderList.tracking
     *
     * @mbggenerated
     */
    public String getTracking() {
        return tracking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.tracking
     *
     * @param tracking the value for orderList.tracking
     *
     * @mbggenerated
     */
    public void setTracking(String tracking) {
        this.tracking = tracking == null ? null : tracking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.is_show
     *
     * @return the value of orderList.is_show
     *
     * @mbggenerated
     */
    public Integer getIs_show() {
        return is_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.is_show
     *
     * @param is_show the value for orderList.is_show
     *
     * @mbggenerated
     */
    public void setIs_show(Integer is_show) {
        this.is_show = is_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.pick_up
     *
     * @return the value of orderList.pick_up
     *
     * @mbggenerated
     */
    public Integer getPick_up() {
        return pick_up;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.pick_up
     *
     * @param pick_up the value for orderList.pick_up
     *
     * @mbggenerated
     */
    public void setPick_up(Integer pick_up) {
        this.pick_up = pick_up;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.sharer_id
     *
     * @return the value of orderList.sharer_id
     *
     * @mbggenerated
     */
    public Integer getSharer_id() {
        return sharer_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.sharer_id
     *
     * @param sharer_id the value for orderList.sharer_id
     *
     * @mbggenerated
     */
    public void setSharer_id(Integer sharer_id) {
        this.sharer_id = sharer_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderList.isDelete
     *
     * @return the value of orderList.isDelete
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderList.isDelete
     *
     * @param isDelete the value for orderList.isDelete
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}