package cn.bupt.smartyagl.entity.autogenerate;

public class PayLog extends PayLogKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PayLog.tradeNo
     *
     * @mbggenerated
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PayLog.orderIds
     *
     * @mbggenerated
     */
    private String orderIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PayLog.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PayLog.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PayLog.tradeNo
     *
     * @return the value of PayLog.tradeNo
     *
     * @mbggenerated
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PayLog.tradeNo
     *
     * @param tradeNo the value for PayLog.tradeNo
     *
     * @mbggenerated
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PayLog.orderIds
     *
     * @return the value of PayLog.orderIds
     *
     * @mbggenerated
     */
    public String getOrderIds() {
        return orderIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PayLog.orderIds
     *
     * @param orderIds the value for PayLog.orderIds
     *
     * @mbggenerated
     */
    public void setOrderIds(String orderIds) {
        this.orderIds = orderIds == null ? null : orderIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PayLog.type
     *
     * @return the value of PayLog.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PayLog.type
     *
     * @param type the value for PayLog.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PayLog.status
     *
     * @return the value of PayLog.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PayLog.status
     *
     * @param status the value for PayLog.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}