package cn.bupt.smartyagl.entity.autogenerate;

public class RecentSearch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recentSearch.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recentSearch.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recentSearch.word
     *
     * @mbggenerated
     */
    private String word;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recentSearch.id
     *
     * @return the value of recentSearch.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recentSearch.id
     *
     * @param id the value for recentSearch.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recentSearch.userId
     *
     * @return the value of recentSearch.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recentSearch.userId
     *
     * @param userId the value for recentSearch.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recentSearch.word
     *
     * @return the value of recentSearch.word
     *
     * @mbggenerated
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recentSearch.word
     *
     * @param word the value for recentSearch.word
     *
     * @mbggenerated
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }
}