package cn.bupt.smartyagl.entity.autogenerate;

public class UserScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserScore.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserScore.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserScore.goodsId
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserScore.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserScore.times
     *
     * @mbggenerated
     */
    private Integer times;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserScore.id
     *
     * @return the value of UserScore.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserScore.id
     *
     * @param id the value for UserScore.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserScore.userId
     *
     * @return the value of UserScore.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserScore.userId
     *
     * @param userId the value for UserScore.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserScore.goodsId
     *
     * @return the value of UserScore.goodsId
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserScore.goodsId
     *
     * @param goodsId the value for UserScore.goodsId
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserScore.score
     *
     * @return the value of UserScore.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserScore.score
     *
     * @param score the value for UserScore.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserScore.times
     *
     * @return the value of UserScore.times
     *
     * @mbggenerated
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserScore.times
     *
     * @param times the value for UserScore.times
     *
     * @mbggenerated
     */
    public void setTimes(Integer times) {
        this.times = times;
    }
}